### ISSUE TITLE
[RFC] Separate git repositories 

### ISSUE THREAD

**Issue by Chralu** [thetribeio/generator-project#762]
Hi,

working on the Flutter generator raised a thought I would be happy to discuss.

Backend and Frontend (Mobile App in my case) usually have two separate development workflows. 
They have to remain compatible, but one can be updated without impacting the other.

So I'm wondering if sharing a Git repository is appropriate : it might bring complexity in branches/PR management and setup.

What do you think about it ?

**Comment by jvasseur** [comment]
I'm personally quite partial to monorepos an thing the advantages of having both in the same repo always surpass the disadvantages.

I don't think this is an option we want to have since it will render the logic a lot more complexe in terms of managing docker/CI/deployment configuration that will have to be merged in one case and not the other.

If someone really want to have separate repositories they can run the generator twice in two different repositories (once with only a backend an once with only a frontend).

**Comment by Chralu** [comment]
Ok, I get the constraints. Thanks for replying so fast 👍
